### ISSUE TITLE
Use Optional to demonstrate safer null-checks

### ISSUE THREAD

**Issue by dlew** [dlew/rxjava-multiple-sources-sample#2]

**Comment by dlew** [comment]
Added an example of how this might work in https://github.com/dlew/rxjava-multiple-sources-sample/tree/dlew/optional.

Not sure if I want to merge it at this point.

**Comment by dev4mobile** [comment]
awesome

**Comment by CoXier** [comment]
It seems `Optional<Data>` appears everywhere.
